# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171206_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='identifier',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('hotel', 'identifier')]),
        ),
    ]
