# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='token',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
