# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171210_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
