# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171210_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subTitle', models.CharField(max_length=128)),
                ('hoursFrom', models.TimeField(blank=True, null=True)),
                ('hoursTo', models.TimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Hotel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subServices', to='api.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('scheduleTime', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActionQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='serviceaction',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceActionQuantity'),
        ),
        migrations.AddField(
            model_name='serviceaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.Service'),
        ),
    ]
