# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180104_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaction',
            name='quantity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceActionQuantity'),
        ),
    ]
