# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180104_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Hotel'),
        ),
    ]
