# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-09 12:47
from __future__ import unicode_literals

from django.db import migrations

def populate_admin_users(apps, schema_editor):
    User = apps.get_model('api', 'User')
    AdminUser = apps.get_model('api', 'AdminUser')
    for user in User.objects.all():
        if user.is_superuser:
            admin_user, created = AdminUser.objects.get_or_create(user=user)

def unpopulate_admin_users(app, schema_editor):
    AdminUser = apps.get_model('api', 'AdminUser')
    AdminUser.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_adminuser'),
    ]

    operations = [
        migrations.RunPython(populate_admin_users, unpopulate_admin_users),
    ]
