# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('version', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_filename', models.CharField(max_length=256)),
                ('file_contents', models.TextField(blank=True, default='')),
                ('is_executable', models.BooleanField(default=False)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=64)),
                ('parameter_value', models.CharField(max_length=512)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.Deployment')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(default='master', max_length=256)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='FileDefaultParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField()),
                ('parameter_name', models.CharField(max_length=64)),
                ('parameter_value', models.CharField(blank=True, max_length=512)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.DeploymentFile')),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.CharField(max_length=2048, unique=True)),
                ('local_path', models.CharField(max_length=256, unique=True)),
                ('local_cache', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryBuildOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=256)),
                ('option_command', models.CharField(max_length=1024)),
                ('option_priority', models.IntegerField(default=1)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='RunningDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank='', default='')),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployment_manager.Deployment')),
            ],
        ),
        migrations.AddField(
            model_name='deploymentrepository',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.Repository'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deployment_manager.DeploymentConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='filedefaultparameter',
            unique_together=set([('file', 'parameter_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentrepository',
            unique_together=set([('deployment', 'repo')]),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentfile',
            unique_together=set([('deployment', 'target_filename')]),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentconfig',
            unique_together=set([('name', 'version')]),
        ),
    ]
