# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0002_auto_20180515_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='remotedeploymentmachine',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remotedeploymentmachine',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='disk',
            name='remote_deployment_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', related_query_name='disk', to='deployment_manager.RemoteDeploymentMachine'),
        ),
    ]
