# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0003_auto_20180520_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='local_cache',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='local_path',
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
