# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0004_auto_20180520_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='local_path',
            new_name='name',
        ),
        migrations.AddField(
            model_name='firmware',
            name='remote_deployment_machine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deployment_manager.RemoteDeploymentMachine'),
            preserve_default=False,
        ),
    ]
