# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0005_auto_20180520_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='remote_deployment_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', related_query_name='firmware', to='deployment_manager.RemoteDeploymentMachine'),
        ),
    ]
