# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0006_auto_20180520_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=128)),
                ('remote_deployment_machine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='targets', related_query_name='target', to='deployment_manager.RemoteDeploymentMachine')),
            ],
        ),
        migrations.RemoveField(
            model_name='disk',
            name='remote_deployment_machine',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
