# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0007_auto_20180521_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
    ]
