# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0009_auto_20180603_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningdeployment',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_deployments', related_query_name='running_deployment', to='deployment_manager.Deployment'),
        ),
    ]
