# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployment_manager', '0011_repository_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedeploymentmachine',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='remote_deployment_machines', related_query_name='remote_deployment_machine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remotedeploymentmachine',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
