# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 11:32
from __future__ import unicode_literals

from django.db import migrations
import uuid


def generate_unique_rdm_names(apps, schema_editor):
    RemoteDeploymentMachine = apps.get_model('deployment_manager', 'RemoteDeploymentMachine')
    for row in RemoteDeploymentMachine.objects.all():
        row.name = row.name + '-' + uuid.uuid4()
        row.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0012_auto_20180628_1130'),
    ]

    operations = [
        migrations.RunPython(generate_unique_rdm_names)
    ]
