# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0013_auto_20180628_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedeploymentmachine',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
