# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0014_auto_20180628_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='local_path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
