# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0015_auto_20180708_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentBuildOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=256)),
                ('option_command', models.CharField(max_length=1024)),
                ('option_priority', models.IntegerField(default=1)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_options', related_query_name='build_option', to='deployment_manager.Deployment')),
            ],
        ),
    ]
