# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 11:39
from __future__ import unicode_literals

from django.db import migrations


def replace_users_with_admin_users(apps, schema_editor):
    RemoteDeploymentMachine = apps.get_model('deployment_manager', 'RemoteDeploymentMachine')
    for rdm in RemoteDeploymentMachine.objects.filter(user__isnull=False):
        rdm.admin_user = rdm.user.admin_user
        rdm.save()


def replace_admin_users_with_users(apps, schema_editor):
    RemoteDeploymentMachine = apps.get_model('deployment_manager', 'RemoteDeploymentMachine')
    for rdm in RemoteDeploymentMachine.objects.filter(admin_user__isnull=False):
        rdm.user = rdm.admin_user.user
        rdm.save()

class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0017_remotedeploymentmachine_admin_user'),
    ]

    operations = [
        migrations.RunPython(replace_users_with_admin_users, replace_admin_users_with_users),
    ]
