# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_manager', '0018_auto_20181010_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotedeploymentmachine',
            name='user',
        ),
    ]
